### ISSUE TITLE
Vagrant 1.9.3 version - initialize issue

### ISSUE THREAD

**Issue by poornic** [savishy/vagrant-boxes#19]
I have faced below issue , while using the vagrant 1.9.3 version 

C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_open.rb:21:in 

```
`initialize': The requested address is not valid in its context. - connect(2) for "0.0.0.0" port 4243 (Errno::EADDRNOTAVAIL)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_open.rb:21:in `new'
```

This version not connect to the host 0.0.0.0 instead use host_ip:127.0.0.1 and the fix is available in Vagrant 1.9.4 - [reference](https://github.com/rapid7/metasploitable3/issues/106)

**Comment by savishy** [comment]
After @poornic downgraded to v1.9.2 the issue was resolved. Since this is a problem in vagrant, the only solution is to wait for newer vagrant version to be released.
