### ISSUE TITLE
"docker-host": enable box to work on hyper-v or virtualbox

### ISSUE THREAD

**Issue by vishagilityroots** [savishy/vagrant-boxes#24]
With upgrade to Windows 10 Pro my primary machine is now Hyper-V; need to 
* allow this box to be provisioned via Hyper-V (on Windows 10 Pro) or Virtualbox (on all other machines)
* make cosmetic fixes to machine name

**Comment by savishy** [comment]
References

* [Working with Vagrant and Hyper-V](https://followkman.com/2016/07/27/vagrant-up-on-windows-10-with-hyper-v/)
* [Creating an external virtual switch in hyper-v](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/connect-to-network)

**Comment by savishy** [comment]
A new issue, which is entirely Ubuntu-related: https://github.com/boxcutter/ubuntu/issues/73

Shell provisioning of puppet fails due to above cause.

**Comment by savishy** [comment]
verified working with hyperv provider.
